name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          ini-values: memory_limit=-1
          tools: composer:v2
      - uses: ramsey/composer-install@v3
      - name: Check coding standards
        run: ./vendor/bin/phpcs src --standard=psr2 -sp --colors
